name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        OMR_TARGET: ['x86_64']

    steps:
    - name: Prepare
      run: sudo apt-get install -yq build-essential git unzip ncurses-dev libz-dev libssl-dev python subversion gettext gawk wget curl rsync perl libelf-dev python3 libpython3-stdlib liblzma-dev
    - name: Build toolchain
      env:
        OMR_TARGET: ${{matrix.OMR_TARGET}}
      run: |
        git clone https://github.com/ysurac/openmptcprouter || true
        pwd
        ls
        cd openmptcprouter
        git checkout ${{ env.GITHUB_REF }} || true
        git pull || true
        export OMR_PATH="${{ env.GITHUB_REPOSITORY }}/${{ env.GITHUB_REF }}"
        export OMR_FEED_URL="https://github.com/${{ env.GITHUB_REPOSITORY }}"
        export OMR_FEED_SRC="${{ env.GITHUB_REF }}"
        pwd
        ls
        sh build.sh prepare {tools,toolchain}/install -j6
        #echo -e "$OMR_PRIVKEY" > ~/openmptcprouter/${{ env.OMR_TARGET }}/source/key-build
        #echo -e "$OMR_PUBKEY" > ~/openmptcprouter/${{ env.OMR_TARGET }}/source/key-build.pub
    - name: Build
      run: make IGNORE_ERRORS=m -C ~/openmptcprouter/${{ env.OMR_TARGET }}/source package/{compile,install,index} target/install -j6
      
