name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    strategy:
      matrix:
        OMR_TARGET: ['x86_64','x86']

    steps:
    - name: Prepare
      run: sudo apt-get install -yq build-essential git unzip ncurses-dev libz-dev libssl-dev python subversion gettext gawk wget curl rsync perl libelf-dev python3.5 libpython3.5-stdlib liblzma-dev
    - name: Build toolchain
      env:
        OMR_TARGET: ${{matrix.OMR_TARGET}}
      run: |
        git clone https://github.com/ysurac/openmptcprouter || true
        pwd
        ls
        cd openmptcprouter
        git checkout ${{ github.sha }} || true
        git pull || true
        export OMR_FEED_URL="https://github.com/ysurac/openmptcprouter-feeds"
        export OMR_FEED_SRC="${{ github.sha }}"
        pwd
        ls
        pyenv global 3.5.2
        sh build.sh prepare {tools,toolchain}/install -j6
        #echo -e "$OMR_PRIVKEY" > /home/runner/work/openmptcprouter-feeds/openmptcprouter-feeds/openmptcprouter/${{ env.OMR_TARGET }}/source/key-build
        #echo -e "$OMR_PUBKEY" > /home/runner/work/openmptcprouter-feeds/openmptcprouter-feeds/openmptcprouter/${{ env.OMR_TARGET }}/source/key-build.pub
    - name: Build
      env:
        OMR_TARGET: ${{matrix.OMR_TARGET}}
      run: make IGNORE_ERRORS=m -C /home/runner/work/openmptcprouter-feeds/openmptcprouter-feeds/openmptcprouter/${{ env.OMR_TARGET }}/source package/{compile,install,index} target/install -j1 V=s
      
