name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        OMR_TARGET: ['x86_64']

    steps:
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
    - name: Build toolchain
      env:
        OMR_TARGET: ${{matrix.OMR_TARGET}}
      run: |
        git clone https://github.com/ysurac/openmptcprouter || true
        pwd
        ls
        cd openmptcprouter
        git checkout develop || true
        git pull || true
        export OMR_FEED_URL="https://github.com/ysurac/openmptcprouter-feeds"
        export OMR_FEED_SRC="develop"
        sh build.sh -j1 V=s
        #echo -e "$OMR_PRIVKEY" > /home/runner/work/openmptcprouter-feeds/openmptcprouter-feeds/openmptcprouter/${{ env.OMR_TARGET }}/source/key-build
        #echo -e "$OMR_PUBKEY" > /home/runner/work/openmptcprouter-feeds/openmptcprouter-feeds/openmptcprouter/${{ env.OMR_TARGET }}/source/key-build.pub
      
